### ISSUE TITLE
Training Time Benchmarks

### ISSUE THREAD

**Issue by romesco** [EmptyJackson/policy-guided-diffusion#2]
Hey! Thanks for the nicely organized repo!

Do you have any time benchmarks on number of steps / wallclock time on something like a A6000 / 3090 GPU?
(both for the diffusion training and the agent training)

It would be good to get a sense of how long things need to run before signs-of-life emerge. Thanks!

**Comment by EmptyJackson** [comment]
Hey, happy to hear it's helpful!

To get you started, here's a WandB report of a diffusion training run on walked2d-medium-v2: https://api.wandb.ai/links/flair/ug1ql7n2

It took about 11 hours on an A40 GPU, which should scale linearly with dataset size for other datasets (since the number of epochs is fixed).

I'm also working on public runs for agent training, so I'll add those to the repo soon!

**Comment by XuZhaoyi** [comment]
Hey, how about time benchmaks and results for agent training?  Looking forward to your updates! Thanks a lot!

**Comment by EmptyJackson** [comment]
Super sorry for the delay! We've just released a report containing agent and diffusion model training: https://api.wandb.ai/links/flair/jonpqc2o

All runs were done on a single L40S and train times can be found in the run set. Let me know if you'd like to see anything else!
